config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  namespace :admin do
    resources :locations, :wishes
  end

  resources :wishes do
    collection do
      post :confirm_wish
      get :order_wished_locations
      get :accept_match_request
      get :hand_shake_confirmation
      get :extend_expiry
      get :colloquial_confirmation
    end
  end

  resources :locations do
    collection do
      get :locations
      get :ordered_wishes
    end
  end

  root :to => "home#index"
  devise_for :users, :token_authentication_key => 'authentication_key', :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions"}
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy", :via => [:get, :post]
    get "/users/sign_in", to: "home#index", :via => [:get, :post]
  end
  resources :users
  namespace :admin do
    resources :wishes do
      get :approve, :cancel
    end
    resources :locations
  end


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :wishes , :through => :locations_wishes
  
  validates :name, :presence => true
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_filter :authenticate_user!, :is_admin
  
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:name, :area1, :area2, :caretype, :streetaddress, :streetnumber, :pobox, :zipcode, :ziparea, :city, :phone, :email, :supervisor, :supervisoremail, :supervisorphone, :capacity, :lat, :lng)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  def locations
    @location = Location.where('city = ? and id != ?', params[:id], params[:not_location]).load if params[:wish]
    @c_location = Location.where('id = ?', params[:not_location]).first if params[:wish]
    @location = Location.where('city = ?', params[:id]).load unless params[:wish]
    @wish = Wish.where('user_id = ? and valid_until >= ?', current_user.id, Date.today).first unless current_user.blank?
    render :partial => 'shared/locations' unless params[:wish]
    render :partial => 'shared/locations_map' if params[:wish]
  end

  def ordered_wishes
    @wish = Wish.find_or_create_by_user_id(:user_id => current_user.id, :offer_id => params[:location], :valid_until => params[:valid_until].to_datetime)
    @c_location = Location.where('id = ?', @wish.offer_id).first
    location = Location.find_by_id(params[:id])
    locations_wish = LocationsWish.find_or_create_by_wish_id_and_location_id(@wish.id, location.id)
    LocationsWish.add_sequence(locations_wish)
    @wished_locations = LocationsWish.where('wish_id = ?', @wish.id).load
    render :partial => 'locations/ordered_wish_locations'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:name, :area1, :area2, :caretype, :streetaddress, :streetnumber, :pobox, :zipcode, :ziparea, :city, :phone, :email, :supervisor, :supervisoremail, :supervisorphone, :capacity)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper

  def is_selected(location)
    Wish.find_by_user_id(current_user.id).blank? ? false : LocationsWish.find_by_location_id_and_wish_id(location, Wish.find_by_user_id(current_user.id).id).blank? ? false : true
  end

  def location_name(request, type)
    if type == "from"
      return Location.find_by_id(Wish.valid_wish.find_by_id(request.wish_match_id).offer_id).name
    elsif type == "to"
      return Location.find_by_id(Wish.valid_wish.find_by_id(request.wish_by_id).offer_id).name
    end
  end

end

app/views/admin/locations/_form.html.haml
= simple_form_for([:admin, @location]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :area1
    = f.input :area2
    = f.input :caretype
    = f.input :streetaddress
    = f.input :streetnumber
    = f.input :city
    = f.input :lat
    = f.input :lng
    = f.input :phone
    = f.input :pobox
    = f.input :zipcode
    = f.input :ziparea
    = f.input :email
    = f.input :supervisor
    = f.input :supervisoremail
    = f.input :supervisorphone
    = f.input :capacity

  .form-actions
    = f.button :submit
  #map-container
    .map{:id => 'map'}

:javascript
  var map, fromMarker, toMarker;
  map = L.map('map');

  function leaflet_map(lat, lng) {
    var geocoder = new google.maps.Geocoder();
    var address = $('#location_streetnumber').val() + ' ' + $('#location_streetaddress').val() + ', '+ $('#location_city').val();  //1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK)
        {
          if (lat == null && lng == null ) {
            lat = results[0].geometry.location.lat();
            lng = results[0].geometry.location.lng();
          }
          map.setView([lat, lng], 13);
          $('#location_lat').val(lat);
          $('#location_lng').val(lng);
          var cloudmade_api_key = '#{ENV['LEAFLET_API']}';
          var basemap = L.tileLayer('http://{s}.tile.cloudmade.com/'+ cloudmade_api_key + '/1/256/{z}/{x}/{y}.png',
            {
               maxZoom:18
            }).addTo(map);
          L.marker([lat, lng]).addTo(map);
       }
    });
  }

app/views/admin/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', [:admin, @location]
\|
= link_to 'Back', admin_locations_path


:javascript
  $("#location_city").on({
      focus: function(){
      },
      blur: function() {
        leaflet_map(null, null);
        }
  });
  $(document).ready(function() {
       lat = #{@location.lat};
       lng = #{@location.lng};
       leaflet_map(lat, lng);
  });

app/views/admin/locations/index.html.haml
%h3.header.smaller.lighter.blue
  %i.icon-tag
  Listing locations
= link_to 'New Location', new_admin_location_path, :class => "btn btn-primary"
%br
%br
%table.table.table-condensed
  %tr
    %th Name
    %th Area1
    %th Area2
    %th Caretype
    %th Streetaddress
    %th Streetnumber
    %th Pobox
    %th Zipcode
    %th Ziparea
    %th City
    %th Phone
    %th Email
    %th Supervisor
    %th Supervisoremail
    %th Supervisorphone
    %th Capacity
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.name
      %td= location.area1
      %td= location.area2
      %td= location.caretype
      %td= location.streetaddress
      %td= location.streetnumber
      %td= location.pobox
      %td= location.zipcode
      %td= location.ziparea
      %td= location.city
      %td= location.phone
      %td= location.email
      %td= location.supervisor
      %td= location.supervisoremail
      %td= location.supervisorphone
      %td= location.capacity
      %td= link_to '<i class="btn btn-info icon-search"></i>'.html_safe, [:admin, location]
      %td= link_to '<i class="btn btn-success icon-pencil"></i>'.html_safe, edit_admin_location_path(location)
      %td= link_to '<i class="btn btn-danger icon-remove"></i>'.html_safe, [:admin, location], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/admin/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path


:javascript
  $("#location_city").on({
      focus: function(){
      },
      blur: function() {
        leaflet_map(null, null);
      }
  });

app/views/admin/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Area1:
  = @location.area1
%p
  %b Area2:
  = @location.area2
%p
  %b Caretype:
  = @location.caretype
%p
  %b Streetaddress:
  = @location.streetaddress
%p
  %b Streetnumber:
  = @location.streetnumber
%p
  %b Pobox:
  = @location.pobox
%p
  %b Zipcode:
  = @location.zipcode
%p
  %b Ziparea:
  = @location.ziparea
%p
  %b City:
  = @location.city
%p
  %b Phone:
  = @location.phone
%p
  %b Email:
  = @location.email
%p
  %b Supervisor:
  = @location.supervisor
%p
  %b Supervisoremail:
  = @location.supervisoremail
%p
  %b Supervisorphone:
  = @location.supervisorphone
%p
  %b Capacity:
  = @location.capacity

%p
  %b Latitude:
  = @location.lat

%p
  %b Longitude:
  = @location.lng

= link_to 'Edit', edit_admin_location_path(@location)
\|
= link_to 'Back', admin_locations_path