config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  namespace :admin do
    resources :locations, :wishes
  end

  resources :wishes do
    collection do
      post :confirm_wish
      get :order_wished_locations
      get :accept_match_request
      get :hand_shake_confirmation
      get :extend_expiry
      get :colloquial_confirmation
    end
  end

  resources :locations do
    collection do
      get :locations
      get :ordered_wishes
    end
  end

  root :to => "home#index"
  devise_for :users, :token_authentication_key => 'authentication_key', :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions"}
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy", :via => [:get, :post]
    get "/users/sign_in", to: "home#index", :via => [:get, :post]
  end
  resources :users
  namespace :admin do
    resources :wishes do
      get :approve, :cancel
    end
    resources :locations
  end


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :wishes , :through => :locations_wishes
  
  validates :name, :presence => true
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_filter :authenticate_user!, :is_admin
  
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to [:admin,@location], notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to admin_locations_url }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:name, :area1, :area2, :caretype, :streetaddress, :streetnumber, :pobox, :zipcode, :ziparea, :city, :phone, :email, :supervisor, :supervisoremail, :supervisorphone, :capacity, :lat, :lng)
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  def locations
    @location = Location.where('city = ? and id != ?', params[:id], params[:not_location]).load if params[:wish]
    @c_location = Location.where('id = ?', params[:not_location]).first if params[:wish]
    @location = Location.where('city = ?', params[:id]).load unless params[:wish]
    @wish = Wish.where('user_id = ? and valid_until >= ?', current_user.id, Date.today).first unless current_user.blank?
    render :partial => 'shared/locations' unless params[:wish]
    render :partial => 'shared/locations_map' if params[:wish]
  end

  def ordered_wishes
    @wish = Wish.find_or_create_by_user_id(:user_id => current_user.id, :offer_id => params[:location], :valid_until => params[:valid_until].to_datetime)
    @c_location = Location.where('id = ?', @wish.offer_id).first
    location = Location.find_by_id(params[:id])
    locations_wish = LocationsWish.find_or_create_by_wish_id_and_location_id(@wish.id, location.id)
    LocationsWish.add_sequence(locations_wish)
    @wished_locations = LocationsWish.where('wish_id = ?', @wish.id).load
    render :partial => 'locations/ordered_wish_locations'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def location_params
    params.require(:location).permit(:name, :area1, :area2, :caretype, :streetaddress, :streetnumber, :pobox, :zipcode, :ziparea, :city, :phone, :email, :supervisor, :supervisoremail, :supervisorphone, :capacity)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper

  def is_selected(location)
    Wish.find_by_user_id(current_user.id).blank? ? false : LocationsWish.find_by_location_id_and_wish_id(location, Wish.find_by_user_id(current_user.id).id).blank? ? false : true
  end

  def location_name(request, type)
    if type == "from"
      return Location.find_by_id(Wish.valid_wish.find_by_id(request.wish_match_id).offer_id).name
    elsif type == "to"
      return Location.find_by_id(Wish.valid_wish.find_by_id(request.wish_by_id).offer_id).name
    end
  end

end

app/views/locations/_form.html.haml
= simple_form_for(@location) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :area1
    = f.input :area2
    = f.input :caretype
    = f.input :streetaddress
    = f.input :streetnumber
    = f.input :pobox
    = f.input :zipcode
    = f.input :ziparea
    = f.input :city
    = f.input :phone
    = f.input :email
    = f.input :supervisor
    = f.input :supervisoremail
    = f.input :supervisorphone
    = f.input :capacity
    = f.input :lb
    = f.input :mb

  .form-actions
    = f.button :submit

app/views/locations/_ordered_wish_locations.html.haml
-if @saved_wish.blank?
  %span.badge.badge-success.badge-size
    3
%h3 Ordered Wished Locations
%ul#sortable
  - if @saved_wish.blank?
    :javascript
      $(function() {
        $( "#sortable" ).sortable({
            stop: function() {
            var order_wish_locations = [];
            wish_id = $('#wish_id').val();
            $('li.location-container').each(function(){
               order_wish_locations.push($(this).attr('id'))
            })
            $.ajax({
              url: 'wishes/order_wished_locations?id=' + wish_id + '&order_wish_locations=' + order_wish_locations,
              type: 'get',
              dataType: 'html',
              success: function(data) {
               $('#order-wish').html(data)
              }
            })
            }
        });
        $( "#sortable" ).disableSelection();
      });
  -unless @wished_locations.blank?
    = hidden_field_tag 'h_wished_locations', true
    :javascript
      $('#wish_id').val(#{@wish.id});

      function cloudmadeAjax(newUrl ,output ,count ,mape ,callBack) {
        $.ajax({
          url: newUrl,
          async: false,
          dataType: 'JSONP',
          type: "GET",
          cache: false,
          success: function (response, textStatus, xhr) {
            if (response.status != 0) return;
              output.push(response.route_summary.total_time);
              var point, route, points = [];
              for (var s=0; s<response.route_geometry.length; s++) {
                point = new L.LatLng(response.route_geometry[s][0] , response.route_geometry[s][1]);
                points.push(point);
              }
              route= new L.Polyline(points, {
                weight: 3,
                opacity: 0.5,
                smoothFactor: 1
              }).addTo(mape);
              route.bringToFront();
            }
          });
       }

    -@wished_locations.each_with_index do |location_wish, i|
      %li.location-container{ :id => "#{location_wish.location.id}"}
        %span.badge
          = i + 1
        .span11.order-wish-cont-span3
          .map{:id => "ordered_location-image_#{i + 1}" , :class => "location_image" }
          %p
            %b District-
            %b
              = location_wish.location.city
            \/ #{location_wish.location.name}
        :javascript
          $(function () {
            if(!#{@wished_locations.blank?}){
              var output = [];
              var cloudmade_api_key = '#{ENV['LEAFLET_API']}';
              var map, fromMarker, toMarker;

              map = L.map("ordered_location-image_#{i + 1}").setView([#{@c_location.lat}, #{@c_location.lng}], 10);
              var basemap = L.tileLayer('http://{s}.tile.cloudmade.com/'+ cloudmade_api_key + '/1/256/{z}/{x}/{y}.png',
                {
                  maxZoom:18
                }).addTo(map);

              fromMarker = new L.Marker(new L.latLng([#{@c_location.lat},#{@c_location.lng}])).addTo(map);
              toMarker =  new L.Marker(new L.latLng([#{location_wish.location.lat},#{location_wish.location.lng}])).addTo(map);

              cloudmadeAjax('http://routes.cloudmade.com/' + cloudmade_api_key +'/api/0.3/' + fromMarker.getLatLng().lat + ',' + fromMarker.getLatLng().lng + ',' + toMarker.getLatLng().lat + ',' + toMarker.getLatLng().lng + '/car.js?callback?' , output, #{i + 1} ,map ,function (myRtn) {
                getRoute(myRtn);
              });
            }
          });

app/views/locations/edit.html.haml
%h1 Editing location

= render 'form'

= link_to 'Show', @location
\|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Listing locations

%table
  %tr
    %th Name
    %th Area1
    %th Area2
    %th Caretype
    %th Streetaddress
    %th Streetnumber
    %th Pobox
    %th Zipcode
    %th Ziparea
    %th City
    %th Phone
    %th Email
    %th Supervisor
    %th Supervisoremail
    %th Supervisorphone
    %th Capacity
    %th
    %th
    %th

  - @locations.each do |location|
    %tr
      %td= location.name
      %td= location.area1
      %td= location.area2
      %td= location.caretype
      %td= location.streetaddress
      %td= location.streetnumber
      %td= location.pobox
      %td= location.zipcode
      %td= location.ziparea
      %td= location.city
      %td= location.phone
      %td= location.email
      %td= location.supervisor
      %td= location.supervisoremail
      %td= location.supervisorphone
      %td= location.capacity
      %td= link_to 'Show', location
      %td= link_to 'Edit', edit_location_path(location)
      %td= link_to 'Destroy', location, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Location', new_location_path

app/views/locations/new.html.haml
%h1 New location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @location.name
%p
  %b Area1:
  = @location.area1
%p
  %b Area2:
  = @location.area2
%p
  %b Caretype:
  = @location.caretype
%p
  %b Streetaddress:
  = @location.streetaddress
%p
  %b Streetnumber:
  = @location.streetnumber
%p
  %b Pobox:
  = @location.pobox
%p
  %b Zipcode:
  = @location.zipcode
%p
  %b Ziparea:
  = @location.ziparea
%p
  %b City:
  = @location.city
%p
  %b Phone:
  = @location.phone
%p
  %b Email:
  = @location.email
%p
  %b Supervisor:
  = @location.supervisor
%p
  %b Supervisoremail:
  = @location.supervisoremail
%p
  %b Supervisorphone:
  = @location.supervisorphone
%p
  %b Capacity:
  = @location.capacity

= link_to 'Edit', edit_location_path(@location)
\|
= link_to 'Back', locations_path