config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do
  namespace :admin do
    resources :locations, :wishes
  end

  resources :wishes do
    collection do
      post :confirm_wish
      get :order_wished_locations
      get :accept_match_request
      get :hand_shake_confirmation
      get :extend_expiry
      get :colloquial_confirmation
    end
  end

  resources :locations do
    collection do
      get :locations
      get :ordered_wishes
    end
  end

  root :to => "home#index"
  devise_for :users, :token_authentication_key => 'authentication_key', :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions"}
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy", :via => [:get, :post]
    get "/users/sign_in", to: "home#index", :via => [:get, :post]
  end
  resources :users
  namespace :admin do
    resources :wishes do
      get :approve, :cancel
    end
    resources :locations
  end


end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Vaihtais.in", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Toiveeni', wishes_path
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Vaihtais.in is a simple daycare exchange service</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar">
			<div class="navbar-inner">
				<div class="container">
					<div class="nav-collapse">
						<ul class="nav">
							<li>
								<%= link_to "Home", root_path %>
							</li>
							<li>
								<%= link_to "Wishes", admin_wishes_path %>
							</li>
							<li>
								<%= link_to "Locations", admin_locations_path %>
							</li>
						</ul>
					</div>
					<% if user_signed_in? %>
					<li class="btn-group right">
						<a data-toggle="dropdown" class="btn btn-small dropdown-toggle" href=""><%= current_user.name %> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to 'Log Out', destroy_user_session_path, :method => 'delete' %>
							</li>

						</ul>
					</li>
					<% end %>

				</div>
			</div>
		</div>
		<div class="container">

			<%= yield %>
		</div>
	</body>
</html>